pragma circom 2.1.5;

include "./mimc.circom";
include "./node_modules/circomlib/circuits/comparators.circom";
include "./node_modules/circomlib/circuits/bitify.circom";

template ClaimTransfer(N) {
    //////////////////////////////////////////////
    // Public outputs
    ///////////////////////////////////////////// 
    signal output xfer_commitment;
    signal output old_balance_commitment;
    signal output new_balance_commitment;

    //////////////////////////////////////////////
    // Public inputs
    //////////////////////////////////////////////
    signal input claimer_addr;
    signal input asset;

    //////////////////////////////////////////////
    // Private inputs
    //////////////////////////////////////////////
    signal input xfer_amt[N];

    // Short lived secret calculated via ECDH between the claimer's long-term 
    // view key and a ephemeral key generated by the sender
    signal input xfer_secret[N];     

    signal input old_balance;
    signal input new_balance;
    signal input balance_secret;

    //////////////////////////////////////////////
    // Component arrays (must be declared at top level)
    //////////////////////////////////////////////
    component XH[N];
    component xfer_amt_bits[N];
    component xfer_amt_gtz[N];

    //////////////////////////////////////////////
    // Xfer commitments (individual + combined)
    //////////////////////////////////////////////
    signal xfer_commitments[N];
    
    for (var i = 0; i < N; i++) {
        XH[i] = MiMC_Sum(4);
        XH[i].msgs[0] <== claimer_addr;
        XH[i].msgs[1] <== asset;
        XH[i].msgs[2] <== xfer_amt[i];
        XH[i].msgs[3] <== xfer_secret[i];
        xfer_commitments[i] <== XH[i].out;
    }
    
    // Combined commitment to all xfer commitments
    component CombinedXH = MiMC_Sum(N);
    for (var i = 0; i < N; i++) {
        CombinedXH.msgs[i] <== xfer_commitments[i];
    }
    xfer_commitment <== CombinedXH.out;

    component OH = MiMC_Sum(4);
    OH.msgs[0] <== claimer_addr;
    OH.msgs[1] <== asset;
    OH.msgs[2] <== old_balance;
    OH.msgs[3] <== balance_secret;
    old_balance_commitment <== OH.out;

    component NH = MiMC_Sum(4);
    NH.msgs[0] <== claimer_addr;
    NH.msgs[1] <== asset;
    NH.msgs[2] <== new_balance;
    NH.msgs[3] <== balance_secret;
    new_balance_commitment <== NH.out;

    //////////////////////////////////////////////
    // Range checks (64-bit values)
    //////////////////////////////////////////////
    
    var total_xfer_amt = 0;
    
    for (var i = 0; i < N; i++) {
        // Prove xfer_amt[i] is within 64-bit range
        xfer_amt_bits[i] = Num2Bits(64);
        xfer_amt_bits[i].in <== xfer_amt[i];
        
        // Prove xfer_amt[i] > 0 (strictly positive)
        xfer_amt_gtz[i] = GreaterThan(64);
        xfer_amt_gtz[i].in[0] <== xfer_amt[i];
        xfer_amt_gtz[i].in[1] <== 0;
        xfer_amt_gtz[i].out === 1;
        
        total_xfer_amt += xfer_amt[i];
    }
    
    // Prove old_balance is within 64-bit range
    component old_balance_bits = Num2Bits(64);
    old_balance_bits.in <== old_balance;
    
    // Prove new_balance is within 64-bit range
    component new_balance_bits = Num2Bits(64);
    new_balance_bits.in <== new_balance;

    old_balance + total_xfer_amt === new_balance;
}

component main {public [claimer_addr]}  = ClaimTransfer(1);
