pragma circom 2.1.5;

include "./mimc.circom";
include "./node_modules/circomlib/circuits/comparators.circom";
include "./node_modules/circomlib/circuits/bitify.circom";

template ClaimTransfer() {
    //////////////////////////////////////////////
    // Public outputs
    ///////////////////////////////////////////// 
    signal output xfer_commitment;
    signal output old_balance_commitment;
    signal output new_balance_commitment;

    //////////////////////////////////////////////
    // Public inputs
    //////////////////////////////////////////////
    signal input claimer_addr;
    signal input asset;

    //////////////////////////////////////////////
    // Private inputs
    //////////////////////////////////////////////
    signal input xfer_amt;

    // Short lived secret calculated via ECDH between the claimer's long-term 
    // view key and a ephemeral key generated by the sender
    signal input xfer_secret;     

    signal input old_balance;
    signal input new_balance;
    signal input balance_secret;

    //////////////////////////////////////////////
    // Commitments
    //////////////////////////////////////////////
    component XH = MiMC_Sum(4);
    XH.msgs[0] <== claimer_addr;
    XH.msgs[1] <== asset;
    XH.msgs[2] <== xfer_amt;
    XH.msgs[3] <== xfer_secret;
    xfer_commitment <== XH.out;

    component OH = MiMC_Sum(4);
    OH.msgs[0] <== claimer_addr;
    OH.msgs[1] <== asset;
    OH.msgs[2] <== old_balance;
    OH.msgs[3] <== balance_secret;
    old_balance_commitment <== OH.out;

    component NH = MiMC_Sum(4);
    NH.msgs[0] <== claimer_addr;
    NH.msgs[1] <== asset;
    NH.msgs[2] <== new_balance;
    NH.msgs[3] <== balance_secret;
    new_balance_commitment <== NH.out;

    //////////////////////////////////////////////
    // Range checks (64-bit values)
    //////////////////////////////////////////////
    
    // Prove xfer_amt is within 64-bit range
    component xfer_amt_bits = Num2Bits(64);
    xfer_amt_bits.in <== xfer_amt;
    
    // Prove old_balance is within 64-bit range
    component old_balance_bits = Num2Bits(64);
    old_balance_bits.in <== old_balance;
    
    // Prove new_balance is within 64-bit range
    component new_balance_bits = Num2Bits(64);
    new_balance_bits.in <== new_balance;
    
    // Prove xfer_amt > 0 (strictly positive)
    component xfer_amt_gtz = GreaterThan(64);
    xfer_amt_gtz.in[0] <== xfer_amt;
    xfer_amt_gtz.in[1] <== 0;
    xfer_amt_gtz.out === 1;

    old_balance + xfer_amt === new_balance;
}

component main {public [claimer_addr]}  = ClaimTransfer();

